on: [push, pull_request]

jobs:
    ci:
      runs-on: ubuntu-latest
      container:
        image: barichello/godot-ci:4.2.2
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: 
          run: |
            tasks./ci.sh
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: build
            path: build