name: ci

on:
    pull_request:
    push:
        branches:
            - main
env:
    godot_version: 4.2.2
    
jobs:
    ci:
      runs-on: ubuntu-latest
      container:
        image: barichello/godot-ci:4.2.2
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Setup
          run: |
            mkdir -v -p ~/.local/share/godot/export_templates/
            mv /root/.local/share/godot/export_templates/${{env.godot_version}}.stable ~/.local/share/godot/export_templates/${{env.godot_version}}.stable
        - name: ci
          run: |
            tasks/ci.sh
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: build
            path: build